### ISSUE TITLE
Bots without weapons

### ISSUE THREAD

**Issue by slimline33** [ineedbots/cod4x_bot_warfare#37] opened 2024-03-27 16:52 UTC
Hello, I installed version 2.2.0 without MOD on cod4x with NE, but the bots don't have weapons. However, with version 2.1.0, it works perfectly and the bots also have weapons. I don't think I have a configuration problem. 

I hope you can help me through debugging.

![image](https://github.com/ineedbots/iw3_bot_warfare/assets/3323812/790c047d-7903-4e0f-b8a0-34ad7c677b5b)

**Comment by ineedbots** [comment] 2024-03-28 19:08
dupe of #34 

make sure that your cod4x server is running on the latest commit (not release, their release is too old): https://github.com/callofduty4x/CoD4x_Server

**Closed as completed by ineedbots** 2024-03-28 19:08 UTC

**Comment by slimline33** [comment] 2024-03-28 19:10
Hi! Thanks. I read that (https://github.com/callofduty4x/CoD4x_Server/commit/73f58118d9a1d9b9fea80c37946dc58a893ada9f) already and compiled the source from github.

But It does not help. I think it could be a problem also with NE? i also read a comment which said that as soon as a mod / addon changes something in the classes, there could also be problems.
