### ISSUE TITLE
Bots get stuck in each other

### ISSUE THREAD

**Issue by higuita** [ineedbots/cod4x_bot_warfare#45] opened 2024-10-05 02:55 UTC
I added this mod to the openwarfare mod and sometimes, when 2 bots from different teams get too close, they get stuck, they look down, they move a little, but never kill each other. They should use the knife but for some reason they stay there until some human kill them. Any idea what is wrong here? thanks!

**Comment by fonix4000** [comment] 2024-10-26 01:25
I also am seeing this issue

**Comment by fonix4000** [comment] 2024-10-27 18:16
Found the "cause" of the bug. When bots mantle over walls etc, their gun is removed from their hand until they die, particularly noticable on killhouse.

**Comment by ineedbots** [comment] 2024-10-29 16:17
dupe of #34

**Closed as completed by ineedbots** 2024-10-29 16:17 UTC
